"""Local API for the AccraFlood Random Forest model.

Run from the KOO folder:
    python flood_model_api.py

The API loads flood_model.pkl generated by flood_model_train.py and exposes
POST /predict with elevation_m, slope_deg, and drainage_density.
"""
from __future__ import annotations

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import joblib
import pandas as pd

ROOT = Path(__file__).resolve().parent
# Prefer recomputed model if available, fall back to original
MODEL = None
for candidate in ("flood_model_recomputed_no_drain.pkl", "flood_model_recomputed_with_drain.pkl", "flood_model.pkl"):
    path = ROOT / candidate
    if path.exists():
        MODEL = joblib.load(path)
        print(f"Loaded model: {path.name}")
        break
if MODEL is None:
    raise FileNotFoundError("No flood model found. Place a model pickle in the repository root named 'flood_model_recomputed_no_drain.pkl' or 'flood_model.pkl'.")

# Try to read feature names from the fitted estimator (scikit-learn uses `feature_names_in_`).
if hasattr(MODEL, "feature_names_in_"):
    FEATURES = [str(f) for f in MODEL.feature_names_in_]
else:
    # Fallback to the historical default if the model was fitted without named features
    FEATURES = ["elevation_m", "slope_deg", "drainage_density"]


def risk_level(probability: float) -> str:
    if probability >= 0.67:
        return "high"
    if probability >= 0.34:
        return "moderate"
    return "low"


class FloodModelHandler(BaseHTTPRequestHandler):
    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self) -> None:
        self._send_json(204, {})

    def do_GET(self) -> None:
        if self.path == "/health":
            self._send_json(200, {"status": "ok", "features": FEATURES})
        else:
            self._send_json(404, {"error": "Not found"})

    def do_POST(self) -> None:
        if self.path != "/predict":
            self._send_json(404, {"error": "Not found"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length))
            values = {feature: float(payload[feature]) for feature in FEATURES}
            probability = float(MODEL.predict_proba(pd.DataFrame([values]))[0][1])
            self._send_json(200, {
                "flood_probability": round(probability, 4),
                "risk_percent": round(probability * 100),
                "risk_level": risk_level(probability),
                "features": values,
            })
        except (KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": f"Invalid prediction input: {error}"})
        except Exception as error:
            self._send_json(500, {"error": f"Prediction failed: {error}"})

    def log_message(self, format: str, *args: object) -> None:
        print(f"[flood-model-api] {format % args}")


if __name__ == "__main__":
    server = ThreadingHTTPServer(("127.0.0.1", 8000), FloodModelHandler)
    print("Flood model API listening at http://127.0.0.1:8000")
    server.serve_forever()